apiVersion: v2
name: keycloak-deploy
type: application

# Follow Semantic Versioning (https://semver.org/)
version: 1.0.0

# Version of application being deployed
appVersion: "24.0.4"


dependencies:
  - name: keycloak
    version: 24.8.1
    repository: https://charts.bitnami.com/bitnami
